name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}} # Put here the owner heroku account API Key
          heroku_app_name: "" # Don't worry about set this param, this first step's just for login in Heroku
          heroku_email: "herehavetheseflowers@gmail.com"
          justlogin: true
      - run: |
          heroku container:login && \
          heroku container:push web --app herehavetheseflowers-vacate && \
          heroku container:release web --app herehavetheseflowers-vacate
